# {{ ansible_managed }}

persistence true
persistence_location /var/lib/mosquitto/
log_dest syslog
log_timestamp true

# publish system information in a regular interval
sys_interval 60

# some information is useful
connection_messages true

password_file /etc/mosquitto/passwd
allow_anonymous false
require_certificate false

{% for connection in mqtt_bridges %}
connection {{ connection.name }}
address {{ connection.address }}:{{ connection.port }}
remote_username {{ connection.user }}
remote_password {{ connection.password }}
{% for topic in connection.topics %}
topic {{ topic }}
{% endfor %}
bridge_capath /etc/ssl/certs
{% endfor %}
