#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'

require 'optparse'
require 'mqtt'
require 'evdev' if RUBY_PLATFORM =~ /linux/
require 'logger'
require 'pathname'

class Buffer
  def initialize(timeout:, logger:)
    @timeout = timeout
    @logger = logger
    reset
  end

  def append(char)
    writing do
      @chars << char
    end
  end

  def chop!
    writing do
      @chars.chop!
    end
  end

  def reset
    @logger.debug(self.class.name) { 'Resetting' }
    @chars = ''
    @last_changed = Time.now
  end

  def empty?
    reading do
      @chars.empty?
    end
  end

  def to_s
    reading do
      @chars.to_s
    end
  end

  private

  #
  # before returning the current content, check if reset is needed because of age
  #
  def reading(&block)
    age = Time.now - @last_changed

    if age > @timeout && !@chars.empty?
      @logger.debug(self.class.name) { "Content is #{age.truncate(1)} s old (max is #{@timeout} s)" }
      reset
    end

    block.call
  end

  # reset if needed and then update the last_changed timestamp
  def writing(&block)
    reading(&block)
  ensure
    @last_changed = Time.now
  end
end

module Commands
  class Base
    def initialize(logger:)
      @logger = logger
    end

    def to_s
      self.class.name
    end

    def debug(message)
      @logger.debug(self) { message }
    end

    def info(message)
      @logger.info(self) { message }
    end

    def warn(message)
      @logger.warn(self) { message }
    end
  end

  class Append < Base
    def initialize(char, logger:)
      super(logger: logger)
      @char = char
    end

    def call(buffer)
      debug "Appending #{@char} to '#{buffer}'"
      buffer.append(@char)
    end
  end

  class DummySend < Base
    def call(buffer)
      return if buffer.empty?
      self.warn "NOT sending '#{buffer}' anywhere"
      buffer.reset
    end
  end

  class Publish < Base
    def initialize(url:, topic:, logger:)
      super(logger: logger)
      @mqtt = MQTT::Client.new(url)
      @mqtt.connect
      @topic = topic
      @logger = logger
    end

    def call(buffer)
      if buffer.empty?
        debug "NOT publishing because buffer is empty"
        return
      end

      debug "Publishing '#{buffer}' to '#{@topic}'"
      @mqtt.publish(@topic, buffer)
      debug "Success"

      buffer.reset
    end
  end

  class Print < Base
    def call(buffer)
      if buffer.empty?
        info 'Buffer is empty'
      else
        info "Buffer is #{buffer}"
      end
    end
  end

  class Chop < Base
    def call(buffer)
      chopped = buffer.chop!
      info "Chopped off #{chopped}"
    end
  end
end

class Keypad
  STATI = %w[released pressed repeated]

  def initialize(device:, timeout: , logger:)
    @keyboard = Evdev.new(device)
    @buffer = Buffer.new(timeout: timeout, logger: logger)
    @logger = logger
    @actions = {
      :KEY_KP0        => Commands::Append.new('0', logger: logger),
      :KEY_KP1        => Commands::Append.new('1', logger: logger),
      :KEY_KP2        => Commands::Append.new('2', logger: logger),
      :KEY_KP3        => Commands::Append.new('3', logger: logger),
      :KEY_KP4        => Commands::Append.new('4', logger: logger),
      :KEY_KP5        => Commands::Append.new('5', logger: logger),
      :KEY_KP6        => Commands::Append.new('6', logger: logger),
      :KEY_KP7        => Commands::Append.new('7', logger: logger),
      :KEY_KP8        => Commands::Append.new('8', logger: logger),
      :KEY_KP9        => Commands::Append.new('9', logger: logger),
      :KEY_KPPLUS     => Commands::Append.new('+', logger: logger),
      :KEY_KPMINUS    => Commands::Append.new('-', logger: logger),
      :KEY_KPASTERISK => Commands::Append.new('*', logger: logger),
      :KEY_KPSLASH    => Commands::Append.new('/', logger: logger),
      :KEY_KPDOT      => Commands::Append.new('.', logger: logger),
      :KEY_NUMLOCK    => Commands::Print.new(logger: logger),
      :KEY_KPENTER    => Commands::DummySend.new(logger: logger),
      :KEY_BACKSPACE  => Commands::Chop.new(logger: logger),
    }
  end

  def register(key, command)
    @actions[key] = command
  end

  def start!
    @logger.debug(self.class.name) { "Registering handlers for #{keys}" }

    @keyboard.on(*keys) do |state, key|
      @logger.debug(self.class.name) { "Key #{key} was #{STATI[state]}" }

      case state
      when 0 # released
        command = command(key)
        @logger.info(self.class.name) { "Calling #{command} with buffer '#{@buffer}'" }
        command.call(@buffer)
      when 1 # pressed
        # ignored
      when 2 # repeated
        # ignored
      else
        raise "Don't know what to do with state #{state}"
      end
    end

    @logger.info(self.class.name) { 'Ready to accept keyboard events' }

    loop do
      begin
        @keyboard.handle_event
      rescue Evdev::AwaitEvent
        Kernel.select([@keyboard.event_channel])
        retry
      rescue Interrupt
        @logger.warn(self.class.name) { "Discarding '#{@buffer}'" } unless @buffer.empty?
        return
      end
    end
  end

  private

  def keys
    @actions.keys
  end

  def command(key)
    @actions.fetch(key)
  end
end

options = {
  keypad: {
    device: '/dev/input/event0',
    timeout: 3,
  },
  mqtt: {
    url: nil,
    topic: nil,
  },
}

logger = Logger.new(STDERR)
logger.level = Logger::FATAL
logger.progname = Pathname(__FILE__).basename

OptionParser.new do |opts|
  opts.banner = <<~EOM
    Publishes keyboard input to an MQTT topic.

    Options:
  EOM
  opts.version = '1.0.0'

  opts.on('--device DEVICE', 'The device file that provides the input') do |device|
    options[:keypad][:device] = device
  end

  opts.on('--timeout SECONDS', 'Timeout in seconds after which input that was not already sent is discarded') do |timeout|
    options[:keypad][:timeout] = timeout.to_i
  end

  opts.on('-v', '--verbose', 'Run verbosely. Repeat for even more verbosity.') do
    logger.level = logger.level - 1 if logger.level > 0
  end

  opts.on('--mqtt MQTT-URI', 'The URI to the MQTT server') do |mqtt|
    options[:mqtt][:url] = mqtt
  end

  opts.on('--topic TOPIC', 'The MQTT topic where the input is published to') do |topic|
    options[:mqtt][:topic] = topic
  end
end.parse!

begin
  kp = Keypad.new(
    device: options[:keypad][:device],
    timeout: options[:keypad][:timeout],
    logger: logger
  )

  kp.register(
    :KEY_KPENTER,
    Commands::Publish.new(
      url: options[:mqtt][:url],
      topic: options[:mqtt][:topic],
      logger: logger
    )
  )
  kp.start!
rescue => err
  warn "Error: #{err.message}"
  logger.error err.backtrace.join("\n")
  exit 1
end

__END__

TODO

* Use MAC address as client ID (there shall be only one keyboard; the last one connecting wins)
* Tests?
* Can we [blink the LED](https://hewner.github.io/2006/08/21/evdev-for-ruby-with-morse-code/)?
