- name: System packages are present
  apt:
    update_cache: yes
    name:
      - libevdev-dev
      - libusb-1.0-0-dev
    state: present
  become: true
  tags: apt

- name: Service template is rendered
  template:
    src: mqtt-keyboard.service.j2
    dest: /etc/systemd/system/mqtt-keyboard.service
    mode: "0664"
  become: true
  tags: systemd, service

- name: Config changes are picked up by systemd
  systemd:
    daemon_reload: yes
  become: true
  tags: systemd, service

- name: Service is enabled and started
  systemd:
    name: mqtt-keyboard.service
    state: restarted
    enabled: true
  become: true
  tags: systemd, service
