# based on https://www.mactopics.de/2017/05/01/der-raspberry-pi-3-als-ibeacon/
- name: Standard software is installed
  apt:
    update_cache: yes
    name:
      - bluez
    state: present
  tags: apt, bluetooth

- name: Bluetooth device is up
  command: hciconfig hci0 up
  become: true
  tags: bluetooth, bluez, hciconfig

- name: Bluetooth device is advertising
  command: hciconfig hci0 leadv 3
  become: true
  tags: bluetooth, bluez, hciconfig

- name: Page and inquiry scan are disabled
  command: hciconfig hci0 noscan
  become: true
  tags: bluetooth, bluez, hciconfig

# Requires a UUID of format 05 91 05 D6 C9 5A 96 A7 69 5C-12 4C 5E 4A 39 AF
# TODO For a regular UUID of format 059105D6-C95A-96A7-695C-124C5E4A39AF:
# ([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})-([0-9A-F]{2})([0-9A-F]{2})-([0-9A-F]{2})([0-9A-F]{2})-([0-9A-F]{2})([0-9A-F]{2})-([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})([0-9A-F]{2})
- name: iBeacon UUIDs are set
  # format is 0x08 0x0008 $IBEACONPROFIX $UUID $MAJOR $MINOR $POWER
  command: "hcitool -i hci0 cmd 0x08 0x0008 1E 02 01 1A 1A FF 4C 00 02 15 {{ item }} 00 00 00 00 C8"
  with_items: "{{ mqtt_beacons }}"
  become: true
  tags: bluetooth, bluez, hcitool
