---
- name: Deploy the mqtt-alarm
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: auto
    app_dir: /opt/shop-alarm

    mqtt_disarm_device: /dev/input/event0
    mqtt_disarm_timeout: 3
    mqtt_disarm_keyboard_topic: werkstatt/keyboard
    mqtt_disarm_status_topic: werkstatt/alarm
    mqtt_disarm_blink1_topic: werkstatt/blink1

  roles:
    - role: mqtt-keyboard
    - role: mqtt-disarm
    - role: mqtt-blink1
    - role: mqtt-router
