---
- name: Deploy the shop alarm system
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_dir: /opt/shop-alarm

    blink1_mqtt_topic: werkstatt/blink1
    lock_mqtt_topic: werkstatt/lock

    keyboard_mqtt_topic: werkstatt/keyboard
    keyboard_device: /dev/input/event0
    keyboard_timeout: 3

    nfc_mqtt_topic: werkstatt/nfc

    pir_mqtt_topic: werkstatt/pir
    pir_gpio: GPIO23

    # mqtt_motion_lock_topic: werkstatt/lock
    # mqtt_motion_status_topic: werkstatt/motion
    #
    # mqtt_telegram_mqtt_topic: werkstatt/telegram

  roles:
    - role: mqtt-blink1
    - role: mqtt-keyboard
    - role: mqtt-lock
    - role: mqtt-nfc
    - role: mqtt-pir
    - role: iBeacon

# TODO
#    - role: mqtt-motion
#    - role: mqtt-telegram
