---
- name: Deploy the shop alarm system
  hosts: all
  become: true
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_dir: "{{ ansistrano_deploy_to }}/current"

    blink1_mqtt_topic: werkstatt/blink1
    lock_mqtt_topic: werkstatt/lock

    keyboard_mqtt_topic: werkstatt/keyboard
    keyboard_device: /dev/input/event0
    keyboard_timeout: 3

    nfc_mqtt_topic: werkstatt/nfc

    pir_mqtt_topic: werkstatt/pir
    pir_gpio: GPIO23

    # motion_mqtt_topic: werkstatt/motion
    # mqtt_telegram_mqtt_topic: werkstatt/telegram

  roles:
    - role: iBeacon
      vars:
        iBeacon_guids:
          - 05 91 05 D6 C9 5A 96 A7 69 5C-12 4C 5E 4A 39 AF
    - role: ansistrano.deploy
      become: false
      vars:
        ansistrano_deploy_from: "{{ playbook_dir }}/../src/"
        ansistrano_deploy_to: /opt/shop-alarm
        ansistrano_current_via: symlink
        ansistrano_deploy_via: rsync
        ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/roles/shop-alarm/tasks/owner.yml"
        ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/shop-alarm/tasks/main.yml"
    - role: mqtt-blink1
    - role: mqtt-keyboard
    - role: mqtt-lock
#    - role: mqtt-motion
    - role: mqtt-nfc
    - role: mqtt-pir
#    - role: mqtt-telegram
