- name: udev rules for blink1 are present
  copy:
    src: 51-blink1.rules
    dest: /etc/udev/rules.d/
    mode: "0644"
  register: udev_rule_files
  tags: blink1, udev

- name: Apply udev rules
  shell:
    cmd: udevadm control --reload-rules
  become: true
  when: udev_rule_files is changed
  tags: blink1, udev

- name: Notify user of the need to unplug and replug the blink1 device
  debug:
    msg: Unplug and replug in the blink1 device
  when: udev_rule_files is changed
  tags: blink1, udev, notification

- name: Service template is rendered
  template:
    src: mqtt-blink1.service.j2
    dest: /etc/systemd/system/mqtt-blink1.service
    mode: "0664"
  become: true
  tags: systemd, service

- name: Config changes are picked up by systemd
  systemd:
    daemon_reload: yes
  become: true
  tags: systemd, service

- name: Service is enabled and started
  systemd:
    name: mqtt-blink1.service
    state: restarted
    enabled: true
  become: true
  tags: systemd, service
