# frozen_string_literal: true

source 'https://rubygems.org'

gem 'evdev' if RUBY_PLATFORM =~ /linux/
gem 'mqtt'
gem 'http', '~> 4.3'
# gem 'rb-blink1'

group :development do
  gem 'bundler', '~> 2.1'
  gem 'guard', '~> 2.16'
  gem 'guard-bundler', '~> 3.0'
  gem 'guard-rspec', '~> 4.7'
  gem 'pry', '~> 0.12'
  gem 'pry-byebug', '~> 3.7'
  gem 'rake', '~> 13'
  gem 'rspec', '~> 3.9'
  gem 'rubocop', '~> 0.79'
  gem 'rubocop-rspec', '~> 1.37'
end
