# frozen_string_literal: true

source 'https://rubygems.org'

gem 'evdev' if RUBY_PLATFORM =~ /linux/
gem 'mqtt'
gem 'http'
gem 'rb-blink1'

group :development do
  gem 'bundler'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rspec'
  gem 'pry'
  gem 'pry-byebug'
  gem 'rake'
  gem 'rspec'
  gem 'rspec-eventually'
  gem 'rubocop'
  gem 'rubocop-rspec'
end
