- name: Service template is rendered
  template:
    src: mqtt-disarm.service.j2
    dest: /etc/systemd/system/mqtt-disarm.service
    mode: "0664"
  become: true
  tags: systemd, service

- name: Config changes are picked up by systemd
  systemd:
    daemon_reload: yes
  become: true
  tags: systemd, service

- name: Service is enabled
  systemd:
    name: mqtt-disarm.service
    enabled: true
  become: true
  tags: systemd, service

- name: Service is restarted
  systemd:
    name: mqtt-disarm.service
    state: restarted
  become: true
  tags: systemd, service
